CREATE TABLE USER_T (
  ID         NUMBER PRIMARY KEY,
  USER_NAME        VARCHAR(50) NOT NULL,
  PASSWORD         VARCHAR(50) NOT NULL,
  COUNTRY          VARCHAR(50) NOT NULL,
  USER_TYPE   NVARCHAR2(50) NOT NULL CHECK(USER_TYPE = 'ADMIN' OR USER_TYPE = 'USER')
)
