CREATE TABLE HOTEL (
  ID         NUMBER PRIMARY KEY,
  HOTEL_NAME        VARCHAR(50) NOT NULL,
  COUNTRY           VARCHAR(50) NOT NULL,
  CITY              VARCHAR(50) NOT NULL,
  STREET   VARCHAR(50) NOT NULL
)
